In [1]:
import pandas as pd

In [2]:
movie=pd.read_csv("top10K-TMDB-movies.csv")

In [5]:
movie.sample(5)

id                title                                  genre  \
1812   10975     Operation Condor        Action,Adventure,Crime,Thriller   
251   568160  Weathering with You        Animation,Drama,Fantasy,Romance   
4659  547565      The Night House                Horror,Thriller,Mystery   
1455     345       Eyes Wide Shut                 Drama,Thriller,Mystery   
6670    9349    Universal Soldier  Thriller,Action,Science Fiction,Crime   

     original_language                                           overview  \
1812                cn  Hired by a Spanish baron, Hong Kong treasure h...   
251                 ja  The summer of his high school freshman year, H...   
4659                en  Reeling from the unexpected death of her husba...   
1455                en  After Dr. Bill Harford's wife, Alice, admits t...   
6670                en  An American soldier who had been killed during...   

      popularity release_date  vote_average  vote_count  
1812      20.475   1991-02-07           7.4         406  
251      120.378   2019-06-19           8.1        1512  
4659      21.278   2021-07-15           6.7         676  
1455      33.548   1999-07-16           7.5        4853  
6670      27.025   1992-07-10           6.3        1287

In [10]:
filtered_data=movie[['id','title','genre','overview']]

In [17]:
filtered_data['tag']=    filtered_data['overview']+filtered_data['genre']

C:\Users\haseeeb\AppData\Local\Temp\ipykernel_1220\134861247.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['tag']=    filtered_data['overview']+filtered_data['genre']


In [13]:
filtered_data

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre  \
0                                          Drama,Crime   
1                                 Comedy,Drama,Romance   
2                                          Drama,Crime   
3                                    Drama,History,War   
4                                          Drama,Crime   
...                                                ...   
9995                          Action,Adventure,Fantasy   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure   
9997                        Action,Science Fiction,War   
9998                    Adventure,Fantasy,Action,Drama   
9999                             Thriller,Action,Crime   

                                               overview  \
0     Framed in the 1940s for the double murder of h...   
1     Raj is a rich, carefree, happy-go-lucky second...   
2     Spanning the years 1945 to 1955, a chronicle o...   
3     The true story of how businessman Oskar Schind...   
4     In the continuing saga of the Corleone crime f...   
...                                                 ...   
9995  The story follows the adventures of Aang, a yo...   
9996  The sharks take bite out of the East Coast whe...   
9997  During World War II, a brave, patriotic Americ...   
9998  A man named Farmer sets out to rescue his kidn...   
9999  Seeking justice for his partner’s murder by an...   

                                                    tag  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 5 columns]

In [19]:
new_data=filtered_data[['id','title','tag']]

In [22]:
new_data.isnull().sum()

id        0
title     0
tag      15
dtype: int64

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000, stop_words='english')
vector=cv.fit_transform(new_data['tag'].values.astype('U')).toarray()

In [31]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
vector.shape

(10000, 1000)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity
similarty=cosine_similarity(vector)

In [51]:
similarty

array([[1.        , 0.10114435, 0.20851441, ..., 0.11616046, 0.16718346,
        0.09325048],
       [0.10114435, 1.        , 0.14552138, ..., 0.        , 0.06482037,
        0.        ],
       [0.20851441, 0.14552138, 1.        , ..., 0.03713907, 0.1069045 ,
        0.13416408],
       ...,
       [0.11616046, 0.        , 0.03713907, ..., 1.        , 0.04962917,
        0.04152274],
       [0.16718346, 0.06482037, 0.1069045 , ..., 0.04962917, 1.        ,
        0.05976143],
       [0.09325048, 0.        , 0.13416408, ..., 0.04152274, 0.05976143,
        1.        ]])

In [52]:
new_data[new_data['title']=='The Godfather']

id          title                                                tag
2  238  The Godfather  Spanning the years 1945 to 1955, a chronicle o...

In [53]:
new_data[new_data['title']=="The Godfather"].index.tolist()
# output np.int64(2)

[2]

In [54]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10000 non-null  int64 
 1   title   10000 non-null  object
 2   tag     9985 non-null   object
dtypes: int64(1), object(2)
memory usage: 234.5+ KB


In [55]:
similarty[2]

array([0.20851441, 0.14552138, 1.        , ..., 0.03713907, 0.1069045 ,
       0.13416408])

In [57]:
sorted(list(enumerate(similarty[2])), reverse=True, key=lambda vector: vector[1])

[(2, np.float64(1.0000000000000002)),
 (4, np.float64(0.5820855000871992)),
 (4569, np.float64(0.5427204202399746)),
 (5010, np.float64(0.5427204202399746)),
 (2624, np.float64(0.5237229365663818)),
 (153, np.float64(0.5185449728701349)),
 (2412, np.float64(0.4666666666666667)),
 (4811, np.float64(0.4666666666666666)),
 (7419, np.float64(0.4666666666666666)),
 (250, np.float64(0.4618802153517007)),
 (330, np.float64(0.4618802153517007)),
 (1133, np.float64(0.4618802153517007)),
 (9520, np.float64(0.4588314677411235)),
 (4360, np.float64(0.4535573676110727)),
 (3670, np.float64(0.4535573676110726)),
 (779, np.float64(0.4427188724235731)),
 (1816, np.float64(0.4310527248642598)),
 (709, np.float64(0.427617987059879)),
 (677, np.float64(0.42426406871192845)),
 (2272, np.float64(0.42426406871192845)),
 (2587, np.float64(0.42426406871192845)),
 (4872, np.float64(0.42426406871192845)),
 (4712, np.float64(0.4221158824088691)),
 (6788, np.float64(0.4221158824088691)),
 (7049, np.float64(0.4221

In [59]:
distance=sorted(list(enumerate(similarty[2])), reverse=True, key=lambda vector: vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
House of Gucci
Batman: The Killing Joke
Bomb City


In [63]:
def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance=sorted(list(enumerate(similarty[index])), reverse=True, key=lambda vector: vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [64]:
recommand("Weathering with You")

Weathering with You
Rascal Does Not Dream of a Dreaming Girl
Groundhog Day
Every Day
Love Wedding Repeat


In [ ]:
import pickle
pickle.dump(new_data,open("movies_list.pkl","wb"))
pickle.dump(similarty,open("similarty.pkl","wb"))
